import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer, Header, Hero,AboutUs,Services, Motives, ContactUs } from '../components'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home - Sanchez Family Cleaning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <Hero/>
        <AboutUs/>
        <Services/>
        <Motives/>
        <ContactUs/>
      </main>
      <Footer/>
    </>
  )
}

export default Home
